# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'curl --user "XHQUOAXB:35836c59-64bd-4633-b74f-2c0f5e45200e" --digest --header "Content-Type: application/json" --include --request GET "https://cloud.mongodb.com/api/atlas/v1.0/groups/5d56db41d5ec131e74b498fc/clusters?pretty=true"'